name: Commit e PR - Principal

on:
  pull_request:
    branches: [ principal ]

jobs:
  testes-unitarios:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '16'
    - name: NPM - Dependências
      run: |
        sudo npm install
    - name: Testes unitários
      run: |
        sudo npm run testes-unitarios
